# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Zombie Apocalypse Simulation
tagline:          'The end'
description:      'description'
url:              zombiea-apocalypse-sim.github.io

author:
  name:           'authors'

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/zombiea-apocalypse-sim/sim
