# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Project ZSB
tagline:          'Simuleren van een apocalypse'
description:      'Zombie apocalypse simulatie software ontwikkeld tijdens het vak Zoeken, Sturen en Bewegen.'
url:              zombiea-apocalypse-sim.github.io

author:
  name:           'Amor Frans, Julian Main, Olaf van Houten en Yorick de Boer'

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/zombiea-apocalypse-sim/sim
redcarpet:
  extensions: ["tables"]
